from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Asset',
    'Transaction',
    'HistoricalData',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Asset': {
        'transactions': 'Transaction',
        'historicalData': 'HistoricalData',
    },
    'Transaction': {
        'asset': 'Asset',
    },
    'HistoricalData': {
        'asset': 'Asset',
    },
}

# fmt: on